### PR TITLE
Set used AZs on Status field

### PR DESCRIPTION
**Pull request by fiunchinho**
It would be cool to add the AZ's being used to create the VMSS in the `Status` field of the `AzureConfig` object.

It feels weird to just copy whatever is in the `Spec` like it's not _real_. So I ended up issuing a request to Azure's API to fetch that info. I don't know if that's the most efficient way. Are there other ways of getting that info?

### CODE REVIEW

**Comment by fiunchinho** [comment]
The question is if we need to put the used AZ's in the Status field, or if we can live without it.

**Comment by fiunchinho** [comment]
You are suggesting creating a new resource that takes the `Status` field from the `AzureConfig` object and sends an HTTP request to the k8s API to update the Status on the API. What would happen when another resource cancels the reconciliation before this resource gets executed? Wouldn't the changes to the status field on the object be lost?

**Comment by tuommaki** [comment]
> You are suggesting creating a new resource that takes the Status field from the AzureConfig object and sends an HTTP request to the k8s API to update the Status on the API. What would happen when another resource cancels the reconciliation before this resource gets executed? Wouldn't the changes to the status field on the object be lost?

This status resource can be prioritized to be executed as one of the first in the resource set.

- If a resource before this one cancels the reconciliation, it probably had a reason and that should be fine.
- If status already contains the AZ, we don't need to fetch it again since it's immutable.
- If status is read from Azure and written to CR status, I think it makes sense to cancel reconciliation at that point. The `UpdateStatus()` change to CR would trigger new reconciliation round immediately.

Does that make sense?

**Comment by fiunchinho** [comment]
I think so. Should we move the checksum logic to this new status resource?

**Comment by tuommaki** [comment]
> Should we move the checksum logic to this new status resource?

Yes, that would probably make a lot of sense. :+1:

**Comment by nprokopic** [comment]
This got a bit outdated now, the change is in unflattened version. Porting it to flattened version or closing? :)

**Comment by fiunchinho** [comment]
Closing for now

**Pull request closed without merging**
