### PR TITLE
Upgrade k8scloudconfig to v10.8.1

### PR DESCRIPTION
**Pull request by ericgraf**
This release of k8scloudconfig includes a change to better detect memory eviction thresholds.

### CODE REVIEW

**Review by MarcelMue — APPROVED** [review]

**Comment by whites11** [comment]
sounds good but please test it before merging

**Comment by whites11** [comment]
> sounds good but please test it before merging

Happy to get you started if you need help

**Review by fiunchinho — APPROVED** [review]
LGTM

**Comment by ericgraf** [comment]
> > sounds good but please test it before merging
> 
> Happy to get you started if you need help

Thanks @whites11 :)  I'll test this change out and report back here.

**Comment by ericgraf** [comment]
@whites11  Confirmed working . I was able to create a WC cluster successfully using base version `v15.0.0` with this version of  azure-operator.

**Pull request merged**
