### PR TITLE
Using new micrologger 0.4.0

### PR DESCRIPTION
**Pull request by tomahawk28**
Introducing new micrologger functions so make logs simpler.

### CODE REVIEW

**Review by whites11 — APPROVED** [review]
Impossible to review, if it is tested LGTM

**Comment by tomahawk28** [comment]
Just asking; how did you usually test provider operator? since project.go have a fixed version.

**Comment by whites11** [comment]
> Just asking; how did you usually test provider operator? since project.go have a fixed version.

In the feature branches we set our version of the operator and we create a new release in the test installation that references it.

**Comment by tomahawk28** [comment]
Tested in `ghost`

**Pull request merged**
