### PR TITLE
Change default etcd data to /var/lib/etcd

### PR DESCRIPTION
**Pull request by fgimenez**

### CODE REVIEW

**Comment by kopiczko** [comment]
That won't work because of self hosted components introduced in 3.1.0 and LB issues we have :(

https://github.com/giantswarm/azure-operator/pull/122

**Comment by fgimenez** [comment]
Ok on it

**Comment by fgimenez** [comment]
Ok, I've pushed here all the required changes, once #122 is merged we can test this one.

**Comment by kopiczko** [comment]
@fgimenez you are now unblocked with you changes. 3.1.0 is merged and works.

**Comment by fgimenez** [comment]
@kopiczko ack, thx, on it.

**Comment by kopiczko** [comment]
Thanks!

**Comment by fgimenez** [comment]
Tested on gollum

**Comment by kopiczko** [comment]
For the record I approved that on slack :)

**Pull request merged**
