### PR TITLE
Updates vendor with k8s 1.9.2

### PR DESCRIPTION
**Pull request by corest**

### CODE REVIEW

**Comment by kopiczko** [comment]
Stale?

**Comment by kopiczko** [comment]
Correct.

**Comment by kopiczko** [comment]
I think you also want to change imorts inside cloudconfig packge.

**Comment by corest** [comment]
I thought about this, but then moved those changes into separate branch, because usually we are not mixing vendoring with version bundle changes

**Comment by kopiczko** [comment]
Yeah. Feel free to proceed with that. You don't need approval for pure vendor updates.

**Pull request merged**
