### PR TITLE
Removed legacy e2e tests

### PR DESCRIPTION
**Pull request by whites11**
Towards: https://github.com/giantswarm/giantswarm/issues/15197

This PR removes the legacy e2e tests in the azure operator repo

I am not sure about the "integration" folder. Should we keep it or was it used for e2e tests as well?

### CODE REVIEW

**Comment by fiunchinho** [comment]
We should keep `integration`. It contains integration tests (surprise) but they don't require a working k8s cluster AFAIK.

**Comment by whites11** [comment]
> We should keep `integration`. It contains integration tests (surprise) but they don't require a working k8s cluster AFAIK.

added them back, thanks

**Review by fiunchinho — APPROVED** [review]

**Comment by fiunchinho** [comment]
Pinging @giantswarm/team-batman-engineers just so that they are aware of this.

**Comment by rossf7** [comment]
Thanks @fiunchinho @whites11 this is great <3

**Pull request merged**
