### PR TITLE
moves status magic to separate files

### PR DESCRIPTION
**Pull request by xh3b4sd**
Just some boyscouting. In the next PR I want to address some improvements for the status management.

### CODE REVIEW

**Comment by xh3b4sd** [comment]
Why does it make it harder for you that way?

**Comment by kopiczko** [comment]
Let's say we have a PR with code calling `setResourceStatus`. I don't know what `setResourceStatus` so I click `View` and search the file for `setResourceStatus`. If this isn't in the same file I have to do other exercises in order to find it out.

I understand people have different workflows and approaches. And brains in general. So if the team likes it I commit.

**Comment by xh3b4sd** [comment]
Most of the time, most of the code presented in a pull request, is never in the same file. We have vastly complex projects with millions of lines of code involved. We will almost never see the code we need to see when viewing the file being changed.

**Comment by xh3b4sd** [comment]
Fishing for LGTM.

**Comment by xh3b4sd** [comment]
Talked with Pawel. We are good.

**Pull request merged**
