### PR TITLE
Add network policy

### PR DESCRIPTION
**Pull request by glitchcrab**
towards giantswarm/giantswarm/issues/4383

### CODE REVIEW

**Comment by glitchcrab** [comment]
tested manually on ghost whilst deploying a TC.

**Comment by glitchcrab** [comment]
and also now deployed to `ghost`.

**Comment by glitchcrab** [comment]
@giantswarm/team-celestial regarding the e2e tests - i'm not too sure why they're failing. do you want them to be green before this is merged?

**Comment by fiunchinho** [comment]
Ignore them for now, we are fixing them. Merge whenever. Thanks

**Pull request merged**
