### PR TITLE
add-all-vnet-service-endpoints

### PR DESCRIPTION
**Pull request by calvix**
request by telecom, should not break anyhting

### CODE REVIEW

**Comment by calvix** [comment]
for some reason workers join cluster after 40 minutes :(

**Comment by calvix** [comment]
that was probably some Azure flakiness

**Comment by JessicaKCriddle** [comment]
Hi @T-Kukawka please could you explain here why this is important so that when a Ludacris team member picks it up they have the background. Thank you

**Comment by calvix** [comment]
this si already done  2o days ago, no need to pick it up

**Comment by T-Kukawka** [comment]
Everything is explained in @JessicaKCriddle: https://github.com/giantswarm/giantswarm/issues/6102

**Pull request merged**
