### PR TITLE
Update k8scc to v10

### PR DESCRIPTION
**Pull request by MarcelMue**
This change REQUIRES the k8s version to be 1.19+ in the release. Upstream removed hyperkube in 1.19 and therefore breaking changes were necessary.

### CODE REVIEW

**Comment by whites11** [comment]
FYI this will have to wait until we finalize release 13.1.0 (hopefully this week).
Anything we should know about this upgrade?

**Comment by MarcelMue** [comment]
> FYI this will have to wait until we finalize release 13.1.0 (hopefully this week).
> Anything we should know about this upgrade?

This is a breaking change because of `hyperkube` going away. It basically means that the operator after this PR will only work with k8s 1.19+

I have no rush merging this and will obviously talk to your team before doing anything :)

**Review by whites11 — APPROVED** [review]
PR wise looks good to me.
Of course needs to be tested properly.

**Comment by MarcelMue** [comment]
PTAL

**Review by tuommaki — APPROVED** [review]

**Pull request merged**
