### PR TITLE
Add changelog entry for NGINX LB Service move

### PR DESCRIPTION
**Pull request by sslavic**
This PR adds changelog entry for changes done in https://github.com/giantswarm/azure-operator/pull/827

Also fixed formatting/nesting for Fixed entries in the Unreleased changelog

### CODE REVIEW

**Comment by sslavic** [comment]
@fiunchinho @whites11 should this go to master and cherry picked to https://github.com/giantswarm/azure-operator/commits/release-4-1-0 branch, or other way around?

**Comment by fiunchinho** [comment]
I guess the best workflow would be to merge into https://github.com/giantswarm/azure-operator/commits/release-4-1-0 branch, which will be merged to master when 4.1.0 is released

**Comment by sslavic** [comment]
thanks @fiunchinho, will create a new branch and PR then based on release-4-1-0

**Comment by sslavic** [comment]
Resurrected as https://github.com/giantswarm/azure-operator/pull/843

**Pull request closed without merging**
