### PR TITLE
Backport drain nodes feature

### PR DESCRIPTION
**Pull request by whites11**
This is a cherry pick of https://github.com/giantswarm/azure-operator/pull/1555 into the 5.8 release branch for platform release 15.1.3

### CODE REVIEW

**Comment by whites11** [comment]
Locally run cncf tests are green.
e2e tests are still failing but it's a platform problem

**Comment by fiunchinho** [comment]
did you try running the e2e tests locally with `go test`?

**Comment by whites11** [comment]
> did you try running the e2e tests locally with `go test`?

I did but some of them were failing like they did with 16.0.2. Maybe it's about how I create the cluster

**Comment by whites11** [comment]
running tests locally fails as well. The problem seems to be with API versions.
For example the `autoscaler_test.go` tries to find a `MachinePool` CR (capi v1alpha4) but can't find any.
I think this is a consequence of the adaptations to make tests to work on CAPZ clusters.

**Comment by whites11** [comment]
tests are green locally

**Review by fiunchinho — APPROVED** [review]

**Pull request merged**
