### PR TITLE
BYOC client: remove AzureClientSet logger

### PR DESCRIPTION
**Pull request by TheoBrigitte**
Towards: https://github.com/giantswarm/giantswarm/issues/3316

### CODE REVIEW

**Comment by TheoBrigitte** [comment]
I does make things a bit easier later on for BYOC

**Comment by xh3b4sd** [comment]
You broke the e2e tests here. How can this happen?

**Comment by xh3b4sd** [comment]
Can I get an answer please?

**Comment by kopiczko** [comment]
Isn't that `Logger:` was still set int `/integration`?

**Comment by TheoBrigitte** [comment]
I did test if ready test compile but forgot about scaling one. I did not ran e2e test here as I thought that was minor change

**Comment by kopiczko** [comment]
To prevent this we can compile integration tests. Uncertain how to do that in architect though. This is very specific build tag.

**Comment by xh3b4sd** [comment]
To me it is pretty easy. 

1. Change integration tests. 
2. Run integration tests. 

2. was just not done. This is the problem.

**Pull request merged**
