### PR TITLE
Use flattened k8scloudconfig

### PR DESCRIPTION
**Pull request by tfussell**
Bringing in https://github.com/giantswarm/k8scloudconfig/pull/692 and https://github.com/giantswarm/k8scloudconfig/pull/711

### CODE REVIEW

**Comment by MarcelMue** [comment]
@giantswarm/team-celestial Are E2E failures currently expected? The ones I checked failed because of context deadline exceeded which seems weird.

**Comment by fiunchinho** [comment]
Yes, I'm fixing them here https://github.com/giantswarm/azure-operator/pull/811

**Comment by fiunchinho** [comment]
If you rebase, e2e tests should pass now. Sorry about that.

**Comment by fiunchinho** [comment]
e2e tests were green last week, we don't need to run them again.

**Pull request merged**
