### PR TITLE
update v5 to k8s 1.12.3

### PR DESCRIPTION
**Pull request by teemow**
* update cloudconfig to 3.7.0
* update container linux amis to 1855.5.0
* edit changelog in versionbundle

### CODE REVIEW

**Comment by teemow** [comment]
This is broken right now because of the missing CIDR configuration for the kube-proxy. See: https://github.com/giantswarm/k8scloudconfig/pull/452#issuecomment-435599184

**Comment by teemow** [comment]
@kopiczko @r7vme any idea how we can solve https://github.com/giantswarm/k8scloudconfig/pull/452#issuecomment-435599184 ?

**Comment by kopiczko** [comment]
In terms on calico CIDR it is computed dynamically based on Vnet network. 

https://github.com/giantswarm/azure-operator/blob/05debd70a4da75cf88d33a82bb97aed7df5529ff/service/controller/v5/resource_set.go#L367-L374

It's basically second half of the range:

https://github.com/giantswarm/azure-operator/blob/05debd70a4da75cf88d33a82bb97aed7df5529ff/service/network/network.go#L26

**Comment by teemow** [comment]
We are turning circles here. I understood how the CIDR is created. The question is how to get this CIDR into the template.

**Comment by kopiczko** [comment]
Let's just meet. I think it will be quicker that way.

**Comment by kopiczko** [comment]
Another try to answer your Q :)

So we have master extension where we render calico manifests: https://github.com/giantswarm/azure-operator/blob/cb4faddc06883c5bb124090d5bb4456408546e9d/service/controller/v5/cloudconfig/master_extension.go#L108

The template is here: https://github.com/giantswarm/azure-operator/blob/cb4faddc06883c5bb124090d5bb4456408546e9d/service/controller/v5/cloudconfig/template.go#L7

**Comment by teemow** [comment]
I was more wondering if there is a way to get the CalicoCIDR into the k8scloudconfig template. I mean at runtime the value must be there anyway.

**Comment by xh3b4sd** [comment]
FYI I pushed a fix for the missing Calico values.

**Comment by calvix** [comment]
looks green
```
 #: k get node
NAME                  STATUS   ROLES    AGE   VERSION
2kytz-master-000000   Ready    master   14m   v1.12.3
2kytz-worker-000001   Ready    <none>   14m   v1.12.3
k[local] ~ | k8s: 2kytz
 #: kk get po
NAME                                         READY   STATUS    RESTARTS   AGE
calico-node-fhcs5                            1/1     Running   0          14m
calico-node-nb4t9                            1/1     Running   0          14m
cert-exporter-588hm                          1/1     Running   0          3m33s
cert-exporter-htzj4                          1/1     Running   0          3m33s
coredns-7996df49d7-8mmp6                     1/1     Running   0          106s
coredns-7996df49d7-nqs98                     1/1     Running   0          106s
default-http-backend-6747cf7b4c-cfw8r        1/1     Running   0          2m59s
default-http-backend-6747cf7b4c-v6thb        1/1     Running   0          2m59s
external-dns-ffffddddd-2b2vs                 0/1     Pending   0          85s
k8s-api-server-2kytz-master-000000           1/1     Running   0          13m
k8s-controller-manager-2kytz-master-000000   1/1     Running   0          13m
k8s-scheduler-2kytz-master-000000            1/1     Running   0          14m
kube-proxy-7l5ld                             1/1     Running   0          14m
kube-proxy-l4t9q                             1/1     Running   0          14m
kube-state-metrics-7b5585d774-gdmh6          2/2     Running   0          3m9s
metrics-server-5c9b5587f5-4x9dt              1/1     Running   0          3m8s
net-exporter-l4pcb                           1/1     Running   0          3m4s
net-exporter-qmbc7                           0/1     Pending   0          95s
nginx-ingress-controller-cf8f7db6b-q4224     1/1     Running   0          2m59s
node-exporter-6nrnf                          1/1     Running   0          2m2s
node-exporter-kwxql                          0/1     Pending   0          103s
```

**Comment by teemow** [comment]
@calvix nice! :rocket: 

please also test upgrading an older cluster to this version.

**Comment by calvix** [comment]
upgraded cluster works also fine

**Pull request merged**
