### PR TITLE
uses incremental deployment mode to preserve k8s LB

### PR DESCRIPTION
**Pull request by xh3b4sd**
Towards https://github.com/giantswarm/azure-operator/issues/233.

### CODE REVIEW

**Comment by xh3b4sd** [comment]
There are still a lot of route writes and they often fail. Uncertain if this is related here. Don't think so. SRE input please.

screen shot 2018-06-13 at 17 31 40

**Comment by r7vme** [comment]
Yes, incremental helps. Standalone resources are now preserved, all good.

But as you posted we still have issue with routes. Kubernetes adds routes into Azure route table, but ARM (azure operator) deletes them. Not sure what we can do here.

**Comment by r7vme** [comment]
> Can we go with this change then and sort the routes issue separately?

Definitely this what we need, even if it's not sorting all the issues.

**Comment by xh3b4sd** [comment]
Ok since the issue with the routes is something else I go with this now.

**Pull request merged**
